/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import control.CadAluno;
import control.CadFunc;
import control.Validacao;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import java.awt.Font;
import javax.swing.JButton;

public class TelaAluno extends javax.swing.JFrame {

	
    public TelaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMat = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCurso = new javax.swing.JTextField();
        jTextFieldRg = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldEnder = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldUF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonSalvar.setFont(new Font("Times New Roman", Font.BOLD, 12));
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldMat1 = new javax.swing.JTextField();
        jTextFieldNome1 = new javax.swing.JTextField();
        jTextFieldCurso1 = new javax.swing.JTextField();
        jTextFieldRg1 = new javax.swing.JTextField();
        jTextFieldCPF1 = new javax.swing.JTextField();
        jTextFieldEnder1 = new javax.swing.JTextField();
        jTextFieldCidade1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelEstado = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButtonSalvarEdt = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane3.setBackground(new java.awt.Color(204, 255, 255));
        jTabbedPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTabbedPane3.setName(""); // NOI18N

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Matricula: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Curso:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("RG:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("CPF:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Endereço:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Cidade :");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("UF:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }

			});
        
        JLabel lblUsuario = new JLabel("Usuario:");
        lblUsuario.setFont(new Font("Times New Roman", Font.BOLD, 12));
        
        JLabel lblSenha = new JLabel("Senha:");
        lblSenha.setFont(new Font("Times New Roman", Font.BOLD, 12));
        
        jTextFieldUsuarioAluno = new JTextField();
        jTextFieldUsuarioAluno.setColumns(10);
        
        jTextFieldSenhaAluno = new JTextField();
        jTextFieldSenhaAluno.setColumns(10);
        
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setFont(new Font("Times New Roman", Font.BOLD, 12));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelarActionPerformed(evt);
			}
		});
        
        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2Layout.setHorizontalGroup(
        	jLayeredPane2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jLayeredPane2Layout.createSequentialGroup()
        			.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jLayeredPane2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jLayeredPane2Layout.createSequentialGroup()
        							.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel2)
        								.addComponent(jLabel3)
        								.addComponent(jLabel4)
        								.addComponent(jLabel5)
        								.addComponent(jLabel6))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(jTextFieldNome, GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        								.addComponent(jTextFieldMat, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jTextFieldCurso)
        								.addComponent(jTextFieldRg, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jTextFieldCPF, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)))
        						.addComponent(jLabel8)
        						.addGroup(jLayeredPane2Layout.createSequentialGroup()
        							.addComponent(jLabel7)
        							.addGap(18)
        							.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jTextFieldEnder, 399, 399, 399)
        								.addGroup(jLayeredPane2Layout.createSequentialGroup()
        									.addComponent(jTextFieldCidade, 320, 320, 320)
        									.addGap(18)
        									.addComponent(jLabel19)
        									.addPreferredGap(ComponentPlacement.UNRELATED)
        									.addComponent(jTextFieldUF, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        								.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.TRAILING, false)
        									.addComponent(jTextFieldSenhaAluno, Alignment.LEADING)
        									.addComponent(jTextFieldUsuarioAluno, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))))
        				.addGroup(jLayeredPane2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblUsuario))
        				.addGroup(jLayeredPane2Layout.createSequentialGroup()
        					.addGap(171)
        					.addComponent(jButtonSalvar, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)
        					.addGap(51)
        					.addComponent(jButtonCancelar, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jLayeredPane2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblSenha)))
        			.addContainerGap(24, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
        	jLayeredPane2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jLayeredPane2Layout.createSequentialGroup()
        			.addGap(33)
        			.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jLayeredPane2Layout.createSequentialGroup()
        					.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jLayeredPane2Layout.createSequentialGroup()
        							.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(jLabel2)
        								.addComponent(jTextFieldMat, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel3)
        								.addComponent(jTextFieldNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addGap(18)
        							.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel4)
        								.addComponent(jTextFieldCurso, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addGap(18)
        							.addComponent(jLabel5))
        						.addComponent(jTextFieldRg, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel6)
        						.addComponent(jTextFieldCPF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addComponent(jLabel7))
        				.addComponent(jTextFieldEnder, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8)
        				.addComponent(jTextFieldCidade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTextFieldUF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel19))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblUsuario)
        				.addComponent(jTextFieldUsuarioAluno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblSenha)
        				.addComponent(jTextFieldSenhaAluno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
        			.addGroup(jLayeredPane2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButtonSalvar)
        				.addComponent(jButtonCancelar))
        			.addContainerGap())
        );
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldMat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldCurso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldRg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldEnder, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldUF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButtonSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane3.addTab("Cadastro", jLayeredPane2);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Matricula: ");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Nome:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Curso:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("RG:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("CPF:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Endereço:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("Cidade:");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Pesquisar");

        jLabelEstado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelEstado.setText("UF :");

        jButtonSalvarEdt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonSalvarEdt.setText("Salvar");

        jButtonExcluir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        
        lblUsuario_1 = new JLabel("Usuario:");
        lblUsuario_1.setFont(new Font("Times New Roman", Font.BOLD, 12));
        
        lblSenha_1 = new JLabel("Senha:");
        lblSenha_1.setFont(new Font("Times New Roman", Font.BOLD, 12));
        
        jTextFieldUsuaAlunEdit = new JTextField();
        jTextFieldUsuaAlunEdit.setColumns(10);
        
        jTextFieldSenhaEdit = new JTextField();
        jTextFieldSenhaEdit.setColumns(10);
        
        jButtonCancelar = new JButton("Cancelar");
        jButtonCancelar.setFont(new Font("Times New Roman", Font.BOLD, 12));

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4Layout.setHorizontalGroup(
        	jLayeredPane4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jLayeredPane4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblSenha_1)
        				.addGroup(jLayeredPane4Layout.createSequentialGroup()
        					.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel11)
        						.addComponent(jLabel12)
        						.addComponent(jLabel13)
        						.addComponent(jLabel14)
        						.addComponent(jLabel15))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jTextFieldNome1, GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        						.addGroup(jLayeredPane4Layout.createSequentialGroup()
        							.addComponent(jTextFieldMat1, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(jButton1))
        						.addComponent(jTextFieldCurso1)
        						.addComponent(jTextFieldRg1, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jTextFieldCPF1, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jLayeredPane4Layout.createSequentialGroup()
        					.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel17)
        						.addGroup(jLayeredPane4Layout.createSequentialGroup()
        							.addGap(53)
        							.addComponent(jButtonSalvarEdt, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jButtonExcluir, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
        						.addGroup(Alignment.TRAILING, jLayeredPane4Layout.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(jTextFieldUsuaAlunEdit, Alignment.LEADING)
        							.addComponent(jTextFieldSenhaEdit, Alignment.LEADING)
        							.addComponent(jTextFieldCidade1, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)))
        					.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jLayeredPane4Layout.createSequentialGroup()
        							.addGap(38)
        							.addComponent(jButtonCancelar))
        						.addGroup(jLayeredPane4Layout.createSequentialGroup()
        							.addGap(93)
        							.addComponent(jLabelEstado)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jTextField2, 20, 20, 20))))
        				.addComponent(lblUsuario_1)
        				.addGroup(jLayeredPane4Layout.createSequentialGroup()
        					.addComponent(jLabel16)
        					.addGap(18)
        					.addComponent(jTextFieldEnder1, 258, 258, 258)))
        			.addGap(47))
        );
        jLayeredPane4Layout.setVerticalGroup(
        	jLayeredPane4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jLayeredPane4Layout.createSequentialGroup()
        			.addGap(32)
        			.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jTextFieldRg1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jLayeredPane4Layout.createSequentialGroup()
        					.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel11)
        						.addComponent(jTextFieldMat1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel12)
        						.addComponent(jTextFieldNome1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel13)
        						.addComponent(jTextFieldCurso1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addComponent(jLabel14)))
        			.addGap(18)
        			.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel15)
        				.addComponent(jTextFieldCPF1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel16)
        				.addComponent(jTextFieldEnder1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jLayeredPane4Layout.createSequentialGroup()
        					.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel17)
        						.addComponent(jLabelEstado)
        						.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(lblUsuario_1)
        					.addGap(18)
        					.addComponent(lblSenha_1))
        				.addGroup(jLayeredPane4Layout.createSequentialGroup()
        					.addComponent(jTextFieldCidade1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jTextFieldUsuaAlunEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jTextFieldSenhaEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(jLayeredPane4Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButtonSalvarEdt)
        				.addComponent(jButtonExcluir)
        				.addComponent(jButtonCancelar))
        			.addContainerGap())
        );
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jTextFieldMat1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jTextFieldNome1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jTextFieldCurso1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jTextFieldRg1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jTextFieldCPF1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jTextFieldEnder1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jTextFieldCidade1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabelEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jButtonSalvarEdt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jButtonExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3Layout.setHorizontalGroup(
        	jLayeredPane3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jLayeredPane3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLayeredPane4, GroupLayout.PREFERRED_SIZE, 459, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(34, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
        	jLayeredPane3Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jLayeredPane4, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 368, Short.MAX_VALUE)
        );
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3.setLayer(jLayeredPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane3.addTab("Editar", jLayeredPane3);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ALUNOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jLabel10, GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(10)
        			.addComponent(jTabbedPane3, GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(22)
        			.addComponent(jLabel10)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jTabbedPane3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(ActionEvent evt) {
       /* 
    	TelaAdmin tela1 = new TelaAdmin();  
        TelaCadFunc tela2 = new TelaCadFunc();
        CadAluno cadastro = new CadAluno();
        */
        System.out.println("teste" + jTextFieldNome.getText());
        
       
        
        this.dispose(); 
         
    }
    
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
		TelaAdmin tela1 = new TelaAdmin(); 
		tela1.setVisible(true);

	}
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvarEdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextFieldUF;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCPF1;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCidade1;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldCurso1;
    private javax.swing.JTextField jTextFieldEnder;
    private javax.swing.JTextField jTextFieldEnder1;
    private javax.swing.JTextField jTextFieldMat;
    private javax.swing.JTextField jTextFieldMat1;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNome1;
    private javax.swing.JTextField jTextFieldRg;
    private javax.swing.JTextField jTextFieldRg1;
    private JTextField jTextFieldUsuarioAluno;
    private JTextField jTextFieldSenhaAluno;
    private JLabel lblUsuario_1;
    private JLabel lblSenha_1;
    private JTextField jTextFieldUsuaAlunEdit;
    private JTextField jTextFieldSenhaEdit;
    private JButton jButtonCancelar;
}
