/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

import control.Acesso;
import control.CadFunc;
import control.Validacao;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;

public class TelaCadFunc extends javax.swing.JFrame {

	TelaAdmin tela = new TelaAdmin();
	public TelaCadFunc() {
		initComponents();

	}

	public boolean botaoAdmin = true;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jLayeredPane1 = new javax.swing.JLayeredPane();
		jLabNome = new javax.swing.JLabel();
		jLabEnder = new javax.swing.JLabel();
		jLabRG = new javax.swing.JLabel();
		jLabCPF = new javax.swing.JLabel();
		jLabNasc = new javax.swing.JLabel();
		jTextFieldNome = new javax.swing.JTextField();
		jTextFieldRG = new javax.swing.JTextField();
		jTextFieldCPF = new javax.swing.JTextField();
		jTextFieldEnder = new javax.swing.JTextField();
		salvar = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jTextFieldSenha = new javax.swing.JTextField();
		jTextFieldNasc = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextFieldUsuario = new javax.swing.JTextField();
		jCheckBoxAdmin = new javax.swing.JCheckBox();
		jCheckBoxOperador = new javax.swing.JCheckBox();
		jLayeredPane2 = new javax.swing.JLayeredPane();
		jLabNome1 = new javax.swing.JLabel();
		jLabNasc1 = new javax.swing.JLabel();
		jLabRG1 = new javax.swing.JLabel();
		jLabCPF1 = new javax.swing.JLabel();
		jLabEnder1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextFieldSenha1 = new javax.swing.JTextField();
		jTextFieldEnder1 = new javax.swing.JTextField();
		jTextFieldCPF1 = new javax.swing.JTextField();
		jTextFieldRG1 = new javax.swing.JTextField();
		jTextFieldNasc1 = new javax.swing.JTextField();
		jTextFieldNome1 = new javax.swing.JTextField();
		jLabUsuario = new javax.swing.JLabel();
		jTextFieldUsuario1 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jButtonExcluir = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jCheckBoxAdmin1 = new javax.swing.JCheckBox();
		jCheckBoxOperador1 = new javax.swing.JCheckBox();
		jButtonCancelar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Funcionários");

		jTabbedPane1.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

		jLabNome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabNome.setText("Nome:");

		jLabEnder.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabEnder.setText("Endereço:");

		jLabRG.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabRG.setText("RG:");

		jLabCPF.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabCPF.setText("CPF:");

		jLabNasc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabNasc.setText("Data Nasc.:");

		salvar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		salvar.setText("Salvar");
		salvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				salvarActionPerformed(evt);
			}
		});
		jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabel2.setText("Senha:");

		jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabel4.setText("Usuario:");

		jCheckBoxAdmin.setBackground(new java.awt.Color(255, 255, 255));
		jCheckBoxAdmin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jCheckBoxAdmin.setText("Administrador");
		jCheckBoxAdmin.setSelected(true);
		jCheckBoxAdmin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxAdminActionPerformed(evt);
			}
		});

		jCheckBoxOperador.setBackground(new java.awt.Color(255, 255, 255));
		jCheckBoxOperador.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jCheckBoxOperador.setText("Operador");
		
		jCheckBoxOperador
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jCheckBoxOperadorActionPerformed(evt);
					}
				});

		jButtonCancelar.setText("Cancelar");
		jButtonCancelar.setFont(new Font("Times New Roman", Font.BOLD, 12));
		jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(
				jLayeredPane1);
		jLayeredPane1Layout
				.setHorizontalGroup(jLayeredPane1Layout
						.createParallelGroup(Alignment.TRAILING)
						.addGroup(
								jLayeredPane1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(
																jLayeredPane1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabNome)
																		.addGap(37)
																		.addComponent(
																				jTextFieldNome,
																				GroupLayout.DEFAULT_SIZE,
																				317,
																				Short.MAX_VALUE))
														.addGroup(
																jLayeredPane1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jLayeredPane1Layout
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addComponent(
																								jLabNasc)
																						.addComponent(
																								jLabEnder)
																						.addComponent(
																								jLabRG)
																						.addComponent(
																								jLabCPF))
																		.addGroup(
																				jLayeredPane1Layout
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addGroup(
																								jLayeredPane1Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												ComponentPlacement.UNRELATED)
																										.addComponent(
																												jTextFieldNasc,
																												319,
																												319,
																												319))
																						.addGroup(
																								jLayeredPane1Layout
																										.createSequentialGroup()
																										.addGap(11)
																										.addGroup(
																												jLayeredPane1Layout
																														.createParallelGroup(
																																Alignment.LEADING)
																														.addComponent(
																																jTextFieldRG,
																																318,
																																318,
																																318)
																														.addComponent(
																																jTextFieldCPF,
																																318,
																																318,
																																318)
																														.addComponent(
																																jTextFieldEnder,
																																318,
																																318,
																																318)
																														.addComponent(
																																jTextFieldUsuario,
																																318,
																																318,
																																318)))))
														.addGroup(
																jLayeredPane1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addGap(0,
																				344,
																				Short.MAX_VALUE))
														.addGroup(
																jLayeredPane1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addGap(34)
																		.addGroup(
																				jLayeredPane1Layout
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addComponent(
																								jTextFieldSenha,
																								317,
																								317,
																								317)
																						.addGroup(
																								jLayeredPane1Layout
																										.createSequentialGroup()
																										.addGroup(
																												jLayeredPane1Layout
																														.createParallelGroup(
																																Alignment.TRAILING)
																														.addComponent(
																																salvar)
																														.addComponent(
																																jCheckBoxAdmin))
																										.addGap(39)
																										.addGroup(
																												jLayeredPane1Layout
																														.createParallelGroup(
																																Alignment.LEADING)
																														.addComponent(
																																jButtonCancelar)
																														.addComponent(
																																jCheckBoxOperador))))))
										.addContainerGap()));
		jLayeredPane1Layout
				.setVerticalGroup(jLayeredPane1Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								jLayeredPane1Layout
										.createSequentialGroup()
										.addGap(27)
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabNome)
														.addComponent(
																jTextFieldNome,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																Alignment.TRAILING)
														.addComponent(jLabNasc)
														.addComponent(
																jTextFieldNasc,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																Alignment.TRAILING)
														.addGroup(
																jLayeredPane1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jLayeredPane1Layout
																						.createParallelGroup(
																								Alignment.BASELINE)
																						.addComponent(
																								jLabRG)
																						.addComponent(
																								jTextFieldRG,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE))
																		.addGap(18)
																		.addComponent(
																				jLabCPF))
														.addComponent(
																jTextFieldCPF,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																Alignment.TRAILING)
														.addComponent(jLabEnder)
														.addComponent(
																jTextFieldEnder,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																Alignment.TRAILING)
														.addComponent(jLabel4)
														.addComponent(
																jTextFieldUsuario,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																Alignment.TRAILING)
														.addComponent(jLabel2)
														.addComponent(
																jTextFieldSenha,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																jCheckBoxAdmin)
														.addComponent(
																jCheckBoxOperador))
										.addPreferredGap(
												ComponentPlacement.RELATED, 28,
												Short.MAX_VALUE)
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(salvar)
														.addComponent(
																jButtonCancelar))
										.addContainerGap()));
		jLayeredPane1.setLayout(jLayeredPane1Layout);
		jLayeredPane1
				.setLayer(jLabNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jLabEnder,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jLabRG, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jLabCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1
				.setLayer(jLabNasc, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jTextFieldNome,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jTextFieldRG,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jTextFieldCPF,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jTextFieldEnder,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(salvar, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jTextFieldSenha,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jTextFieldNasc,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jTextFieldUsuario,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jCheckBoxAdmin,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jCheckBoxOperador,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTabbedPane1.addTab("Cadastro", jLayeredPane1);

		jLabNome1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabNome1.setText("Nome:");

		jLabNasc1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabNasc1.setText("Data Nasc.:");

		jLabRG1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabRG1.setText("RG:");

		jLabCPF1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabCPF1.setText("CPF:");

		jLabEnder1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabEnder1.setText("Endereço:");

		jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabel3.setText("Senha:");

		jLabUsuario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jLabUsuario.setText("Usuario:");

		jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jButton2.setText("Salvar");

		jButtonExcluir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jButtonExcluir.setText("Excluir");

		jButton4.setBackground(new java.awt.Color(255, 153, 153));
		jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jButton4.setText("Pesquisar");

		jCheckBoxAdmin1.setBackground(new java.awt.Color(255, 255, 255));
		jCheckBoxAdmin1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jCheckBoxAdmin1.setText("Administrador");

		jCheckBoxOperador1.setBackground(new java.awt.Color(255, 255, 255));
		jCheckBoxOperador1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jCheckBoxOperador1.setText("Operador");

		jButtonCancelar = new JButton("Cancelar");
		jButtonCancelar.setFont(new Font("Times New Roman", Font.BOLD, 12));

		javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(
				jLayeredPane2);
		jLayeredPane2Layout
				.setHorizontalGroup(jLayeredPane2Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								jLayeredPane2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(
																jLayeredPane2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabNasc1)
																		.addPreferredGap(
																				ComponentPlacement.UNRELATED)
																		.addComponent(
																				jTextFieldNasc1,
																				318,
																				318,
																				318)
																		.addGap(11))
														.addGroup(
																jLayeredPane2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabNome1)
																		.addGap(37)
																		.addComponent(
																				jTextFieldNome1,
																				317,
																				317,
																				317)
																		.addContainerGap())
														.addGroup(
																jLayeredPane2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabCPF1)
																		.addPreferredGap(
																				ComponentPlacement.RELATED,
																				GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jTextFieldCPF1,
																				GroupLayout.PREFERRED_SIZE,
																				194,
																				GroupLayout.PREFERRED_SIZE)
																		.addGap(44)
																		.addComponent(
																				jButton4)
																		.addGap(47))
														.addGroup(
																jLayeredPane2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabRG1)
																		.addGap(50)
																		.addComponent(
																				jTextFieldRG1,
																				318,
																				318,
																				318)
																		.addContainerGap())
														.addGroup(
																jLayeredPane2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabEnder1)
																		.addGap(19)
																		.addComponent(
																				jTextFieldEnder1,
																				318,
																				318,
																				318)
																		.addContainerGap())
														.addGroup(
																jLayeredPane2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabUsuario)
																		.addGap(28)
																		.addComponent(
																				jTextFieldUsuario1,
																				316,
																				316,
																				316)
																		.addContainerGap())
														.addGroup(
																jLayeredPane2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addGap(34)
																		.addGroup(
																				jLayeredPane2Layout
																						.createParallelGroup(
																								Alignment.LEADING,
																								false)
																						.addGroup(
																								jLayeredPane2Layout
																										.createSequentialGroup()
																										.addGroup(
																												jLayeredPane2Layout
																														.createParallelGroup(
																																Alignment.LEADING)
																														.addGroup(
																																jLayeredPane2Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jCheckBoxAdmin1)
																																		.addGap(39)
																																		.addComponent(
																																				jCheckBoxOperador1))
																														.addComponent(
																																jTextFieldSenha1,
																																317,
																																317,
																																317))
																										.addContainerGap())
																						.addGroup(
																								jLayeredPane2Layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton2)
																										.addGap(36)
																										.addComponent(
																												jButtonExcluir)
																										.addPreferredGap(
																												ComponentPlacement.RELATED,
																												GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												jButtonCancelar,
																												GroupLayout.PREFERRED_SIZE,
																												81,
																												GroupLayout.PREFERRED_SIZE)
																										.addGap(34)))))));
		jLayeredPane2Layout
				.setVerticalGroup(jLayeredPane2Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								jLayeredPane2Layout
										.createSequentialGroup()
										.addGap(37)
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																Alignment.TRAILING)
														.addComponent(jLabCPF1)
														.addGroup(
																jLayeredPane2Layout
																		.createParallelGroup(
																				Alignment.BASELINE)
																		.addComponent(
																				jTextFieldCPF1,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton4)))
										.addGap(18)
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabNome1)
														.addComponent(
																jTextFieldNome1,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabNasc1)
														.addComponent(
																jTextFieldNasc1,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabRG1)
														.addComponent(
																jTextFieldRG1,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																jLabEnder1)
														.addComponent(
																jTextFieldEnder1,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																jLabUsuario)
														.addComponent(
																jTextFieldUsuario1,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jTextFieldSenha1,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																jCheckBoxAdmin1)
														.addComponent(
																jCheckBoxOperador1))
										.addGap(9)
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jButton2)
														.addComponent(
																jButtonExcluir)
														.addComponent(
																jButtonCancelar))
										.addContainerGap(
												GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jLayeredPane2.setLayout(jLayeredPane2Layout);
		jLayeredPane2.setLayer(jLabNome1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jLabNasc1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jLabRG1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2
				.setLayer(jLabCPF1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jLabEnder1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jTextFieldSenha1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jTextFieldEnder1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jTextFieldCPF1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jTextFieldRG1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jTextFieldNasc1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jTextFieldNome1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jLabUsuario,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jTextFieldUsuario1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2
				.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jButtonExcluir,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2
				.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jCheckBoxAdmin1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(jCheckBoxOperador1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTabbedPane1.addTab("Editar", jLayeredPane2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap()
								.addComponent(jTabbedPane1).addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jTabbedPane1).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void salvarActionPerformed(java.awt.event.ActionEvent evt) {
	
		TelaCadFunc tela2 = new TelaCadFunc();
		CadFunc cadastro = new CadFunc();
		Validacao validacao = new Validacao();
		System.out.println("teste" + jTextFieldNome.getText());

		if (validacao.valida(jTextFieldNome.getText(),
				jTextFieldNasc.getText(), jTextFieldRG.getText(),
				jTextFieldCPF.getText(), jTextFieldEnder.getText(),
				jTextFieldUsuario.getText(), jTextFieldSenha.getText()) == true) {
			cadastro.salvarLista(jTextFieldNome.getText(),
					jTextFieldNasc.getText(), jTextFieldRG.getText(),
					jTextFieldCPF.getText(), jTextFieldEnder.getText(),
					jTextFieldUsuario.getText(), jTextFieldSenha.getText(), botaoAdmin);
			tela.setVisible(true);
		} else {
			JOptionPane.showMessageDialog(null, "Preencha todos os campos");
			tela2.setVisible(true);
		}

		this.dispose();

	}

	public boolean jCheckBoxAdminActionPerformed(java.awt.event.ActionEvent evt) {
		
		if (jCheckBoxAdmin.isSelected() == true) {
			jCheckBoxOperador.setSelected(false);
			
			botaoAdmin = true;
		}else{
			jCheckBoxAdmin.setSelected(true);
			jCheckBoxOperador.setSelected(false);
			botaoAdmin = true;
		}
		System.out.println(botaoAdmin);
		return botaoAdmin;
	}

	public boolean jCheckBoxOperadorActionPerformed(
			java.awt.event.ActionEvent evt) {
		
		if (jCheckBoxOperador.isSelected() == true) {
			
			jCheckBoxAdmin.setSelected(false);
			botaoAdmin = false;
			
		}else{
			jCheckBoxAdmin.setSelected(false);
			jCheckBoxOperador.setSelected(true);
			botaoAdmin = false;
		}
		System.out.println(botaoAdmin);
		return botaoAdmin;
	}

	private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
		tela.setVisible(true);

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton salvar;
	private javax.swing.JButton jButton2; 
	private javax.swing.JButton jButtonExcluir;
	private javax.swing.JButton jButton4;
	public javax.swing.JCheckBox jCheckBoxAdmin;
	private javax.swing.JCheckBox jCheckBoxAdmin1;
	private javax.swing.JCheckBox jCheckBoxOperador;
	private javax.swing.JCheckBox jCheckBoxOperador1;
	private javax.swing.JLabel jLabCPF;
	private javax.swing.JLabel jLabCPF1;
	private javax.swing.JLabel jLabEnder;
	private javax.swing.JLabel jLabEnder1;
	private javax.swing.JLabel jLabNasc;
	private javax.swing.JLabel jLabNasc1;
	private javax.swing.JLabel jLabNome;
	private javax.swing.JLabel jLabNome1;
	private javax.swing.JLabel jLabRG;
	private javax.swing.JLabel jLabRG1;
	private javax.swing.JLabel jLabUsuario;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JLayeredPane jLayeredPane2;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField jTextFieldCPF;
	private javax.swing.JTextField jTextFieldCPF1;
	private javax.swing.JTextField jTextFieldEnder;
	private javax.swing.JTextField jTextFieldEnder1;
	private javax.swing.JTextField jTextFieldNasc;
	private javax.swing.JTextField jTextFieldNasc1;
	private javax.swing.JTextField jTextFieldNome;
	private javax.swing.JTextField jTextFieldNome1;
	private javax.swing.JTextField jTextFieldRG;
	private javax.swing.JTextField jTextFieldRG1;
	private javax.swing.JTextField jTextFieldSenha;
	private javax.swing.JTextField jTextFieldSenha1;
	private javax.swing.JTextField jTextFieldUsuario;
	private javax.swing.JTextField jTextFieldUsuario1;
	private JButton jButtonCancelar;
}
